plugins: 
  - jekyll-remote-theme
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.24.0"


title: "WEIRD Psychology Project" 

subtitle: "Religion, Family Structure and the Origins of Individual Freedom and Economic Prosperity"

name: "Joeseph Henrich, Jonathan Schultz"